name: run_forecasting_workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 7 * * 1

jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:
      - name: Create and populate .Renviron
        env:
          FRED_KEY: ${{ secrets.FRED_KEY }}
        run: |
          echo FRED_KEY="$FRED_KEY" >> ~/.Renviron
        shell: bash
      - name: Load repo
        uses: actions/checkout@v2
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.2.2"
      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Install R packages from renv.lock
        uses: r-lib/actions/setup-renv@v2
      - name: Run forecasting workflow script
        run: Rscript main.R
      - name: Commit and push if changes
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git pull
          git add -A
          timestamp=$(date -u)
          git commit -m "Last updated: ${timestamp}" || exit 0
          git push origin main || echo "No changes to commit"
